# Generated by Django 3.2.9 on 2021-12-20 20:34

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=50)),
                ('landlord', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='locataire',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('balance', models.FloatField()),
                ('birth_date', models.DateField()),
                ('town', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='locateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('benefits', models.FloatField()),
                ('birth_date', models.DateField()),
                ('town', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.chambre')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.IntegerField()),
                ('tenant', models.IntegerField()),
                ('landlord', models.IntegerField()),
                ('nbr_persons', models.IntegerField()),
                ('in_date', models.DateField()),
                ('out_date', models.DateField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('p', 'Pending'), ('A', 'Active'), ('E', 'Expired')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ville',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='locataire',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.reservation'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_app.reservation'),
        ),
    ]
