# Generated by Django 3.2.9 on 2021-12-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=50)),
                ('landlord', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.IntegerField()),
                ('tenant', models.IntegerField()),
                ('landlord', models.IntegerField()),
                ('nbr_persons', models.IntegerField()),
                ('in_date', models.DateField()),
                ('out_date', models.DateField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('p', 'Pending'), ('A', 'Active'), ('E', 'Expired')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ville',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Locateur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('benefits', models.FloatField()),
                ('town', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_app.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('balance', models.FloatField()),
                ('town', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_app.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ui_app.reservation'),
        ),
    ]
