# Generated by Django 3.2.9 on 2021-12-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='landlord_id',
            new_name='landlord',
        ),
    ]
